[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
utf16_literal = "0.2.1"

# パニック時にunwindせずプログラムを終了させる
# ビルドバージョンのプロファイル
[profile.dev]
panic = "abort"

# リリースバージョンのプロファイル
[profile.release]
panic = "abort"
